import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import {GameContextProvider} from './game_context';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Todo List</title>
      </head>
      <body className={inter.className}>
        <GameContextProvider>
          {children}
        </GameContextProvider>
      </body>
    </html>
  )
}
